#Config Space Invaders
#Sun Jun 07 11:21:31 ART 2026
fondoGalaxia=Original
musicaFondo=space-invaders.wav
pantallaCompleta=false
sonido=true
teclaDerecha=RIGHT
teclaDisparo=SPACE
teclaIzquierda=LEFT
velocidadInvasores=Media
