#Config Space Invaders
#Sat Jun 06 15:29:19 ART 2026
musicaFondo=space-invaders.wav
pantallaCompleta=true
skinInvasores=Original
skinNave=Roja
skinProyectil=Original
sonido=false
teclaDerecha=RIGHT
teclaDisparo=SPACE
teclaIzquierda=LEFT
velocidadInvasores=R\u00E1pida
