#Config Space Invaders
#Mon Jun 08 08:53:00 ART 2026
fondoGalaxia=Ciudad
musicaFondo=space-invaders.wav
pantallaCompleta=false
skinInvasores=Alternativa
skinNave=Oceano
sonido=true
teclaDerecha=RIGHT
teclaDisparo=SPACE
teclaIzquierda=LEFT
tipoProyectil=Laser
velocidadInvasores=Media
velocidadProyectil=R\u00E1pida
